# Generated by Django 2.2.2 on 2020-01-18 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TFModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='模型名称')),
                ('datapath', models.FileField(max_length=200, upload_to=None, verbose_name='模型数据xlsx文件')),
                ('create_time', models.DateTimeField(auto_now=True, null=True, verbose_name='CreateTime')),
                ('rmse', models.FloatField(verbose_name='均方根误差')),
                ('mae', models.FloatField(verbose_name='平均绝对误差')),
            ],
            options={
                'verbose_name': '模型训练数据',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=400, verbose_name='预测数据","号隔开')),
                ('predict', models.FloatField(verbose_name='预测结果')),
                ('expect', models.FloatField(verbose_name='期望结果')),
                ('create_time', models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间')),
                ('isTF', models.BooleanField(default=False, verbose_name='是否训练数据')),
                ('TFModel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sanguis.TFModel', to_field='name', verbose_name='模型')),
            ],
            options={
                'verbose_name': '预测数据',
                'ordering': ['-create_time'],
            },
        ),
    ]
