# Generated by Django 2.2.2 on 2020-01-18 15:03

from django.db import migrations, models
import django.utils.timezone
import sanguis.models.TFModel


class Migration(migrations.Migration):

    dependencies = [
        ('sanguis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='TFModel',
            new_name='model',
        ),
        migrations.AlterField(
            model_name='data',
            name='create_time',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tfmodel',
            name='create_time',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tfmodel',
            name='datapath',
            field=models.FileField(max_length=200, upload_to=sanguis.models.TFModel.uploadto, verbose_name='模型数据xlsx文件'),
        ),
        migrations.AlterField(
            model_name='tfmodel',
            name='mae',
            field=models.FloatField(default=0.0, verbose_name='平均绝对误差'),
        ),
        migrations.AlterField(
            model_name='tfmodel',
            name='rmse',
            field=models.FloatField(default=0.0, verbose_name='均方根误差'),
        ),
    ]
